/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminParticipantsRouteImport } from './routes/admin/participants'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as PagamentoIdRouteImport } from './routes/pagamento.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoIdRoute = PagamentoIdRouteImport.update({
  id: '/pagamento/$id',
  path: '/pagamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inscricao': typeof InscricaoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscricao': typeof InscricaoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inscricao': typeof InscricaoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inscricao'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/settings'
    | '/pagamento/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inscricao'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/settings'
    | '/pagamento/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/inscricao'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/settings'
    | '/pagamento/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InscricaoRoute: typeof InscricaoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  PagamentoIdRoute: typeof PagamentoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$id': {
      id: '/pagamento/$id'
      path: '/pagamento/$id'
      fullPath: '/pagamento/$id'
      preLoaderRoute: typeof PagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InscricaoRoute: InscricaoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  PagamentoIdRoute: PagamentoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
